### PR TITLE
Addressing `base::get` masking error

### PR DESCRIPTION
**Pull request by awong234**
Addresses Issue [#59](https://github.com/rticulate/import/issues/59)

Tests are three: 

1. Test with `get` in calling environment.
1. Test with `get` in arbitrary environment on search path.
1. Test with `get` exported from a package.

The third was accomplished by exporting a function `get` from `packageToTest`.

### CODE REVIEW

**Comment by torfason** [comment]
Thanks for this!

This works locally for me and all checks are passing on GitHub. There three minor issues that I'd like to take care of before pushing to dev:

First: Looking at the tests, I played around with having the masking function fail more explicitly, updating the tests like to have ?`get()` accept any arguments and thus not fail in strange ways, but with an explicit `stop()` with a message.

```r
test_that("Functions named `get` in the calling environment do not mask base::get", {
  get <- function(...) stop("get() in calling environment is masking base::get()")
  expect_silent(import::from(module_base.R, fun1))
  expect_silent(import::from(knitr, normal_print))
  cleanup_environment()
})

test_that("Functions named `get` in arbitrary environment on search path do not mask base::get", {
  attach(what = new.env(parent = emptyenv()), pos = 2, name = "custom")
  assign(x = "get", value = function(...) stop("get() in arbitrary environ is masking base::get()"), pos = "custom")
  expect_silent(import::from(module_base.R, fun1))
  expect_silent(import::from(knitr, normal_print))
  detach("custom")
  cleanup_environment()
})
```

I like this better because it gives an explicit error when the masking function is found. Great to also include a test of this in the custom package, I did not update that to be explicit in this way, it would be great if you felt like updating that in the same way, but that is optional.

Second: It would be great to update NEWS.md as well.

Third: It would also be good to rebase the implementation so that it consists of just three commits:

* Tests (all in a single commit, which is the first commit)
* The code implementation
* Documentation (including news)

Why tests as a first commit? I'm finding that it is very convenient to be able to check out a version with the test but without the fix, so that I can see exactly how they fail before the fix is implemented. It's a variation on TDD (test driven development).

Feel free to do any of this that you are up for. I can address any remaining issues. Thanks again!

**Comment by awong234** [comment]
Will do -- thanks for the great ideas, I can take care of these.

- [x] Rewrite test `get` function to provide informative errors
- [x] Rebase to reorder with tests as first commit
- [x] Update NEWS.md

**Comment by awong234** [comment]
Finished working on the three points -- in the second commit, in `test_from.R` I had to move some cleanup outside of the `test_that` context (line [73](https://github.com/torfason/import/pull/1/commits/9423b1ee2c907d9537a5ea1d9cb63781c85c339d#diff-6956ec7a79d68add4216126f9abb68be03cffac67e856e7e387303845ee001e8R73) and [84](https://github.com/torfason/import/pull/1/commits/9423b1ee2c907d9537a5ea1d9cb63781c85c339d#diff-6956ec7a79d68add4216126f9abb68be03cffac67e856e7e387303845ee001e8R84). This was because the test stops at the first error, those `detach` functions weren't being run, and so every test after that failed. Having the detachments outside of the `test_that` context ensures that the later tests don't fail due to a dirty search path. 

I thought that `testthat` would continue through to the end of the `test_that` block regardless if any `expect_` produced an error -- am I misremembering this? 

Thanks for your review!

**Comment by torfason** [comment]
Thanks again, this looks good to go for integration into dev.

I'll take a look at the the tests as I integrate this. The tests use `testthat` functions, but are not actually run inside the `testthat` harness. Instead, a new process is created for each test file (you could take a look at `.../tests/testthat/test_import.R` if you are interested). This custom harness is pretty rudimentary, in particular, if one test fails, all bets are off.

Again, thanks for doing this, the list of outstanding issues for release is getting quite short.

**Pull request merged**
